import { Flex } from "@chakra-ui/react"
import { Providers } from "./providers/Providers"
import Header from "./components/Header/Header"
import SWRProvider from "./providers/SWRProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <SWRProvider>
            <Flex direction="column" minH="100vh">
              <Header />
              {children}
            </Flex>
          </SWRProvider>
        </Providers>
      </body>
    </html>
  )
}
